### ISSUE TITLE
White page 404

### ISSUE THREAD

**Issue by jensstalder** [phpro/zf-apigility-doctrine-bulk#1]
Nice work!
I created the rpc but when I try to request the route it serves a white 404 Page. (The Service Controller Class is not listed?)

Did I make a mistake?

![screen shot 2015-04-03 at 11 10 41](https://cloud.githubusercontent.com/assets/4964495/6980453/2d7b1c1a-d9f2-11e4-8760-8fc847c770b7.png)
![screen shot 2015-04-03 at 11 12 26](https://cloud.githubusercontent.com/assets/4964495/6980462/5804ab72-d9f2-11e4-849b-7dff831e864c.png)
![screen shot 2015-04-03 at 11 13 06](https://cloud.githubusercontent.com/assets/4964495/6980466/76261c12-d9f2-11e4-9615-1a45673bfb4c.png)

**Comment by veewee** [comment]
Hello @jensstalder,

The controller service class is probably a new key in de apigility configuration. This package hasn't been synced with the latest changes in Apigility for a while. There is also no apgility admin support.
Nevertheless, it should still work with the latest version.

Can you provide me the exception and a trace from the error you are receiving? 
A configuration file could be handy too.

**Comment by jensstalder** [comment]
After a lot of tinkering around I noticed that I made a mistake within the config `doctrine-bulk-handlers`
I needed to utilize the `doctrine.entitymanager.orm_default` entity manager and misspelled my `'CasaLogApi\\V1\\Rpc\\BulkMsg\\BulkMsgController'` Key. Looks like the Module is working as it should. So thanks, this will certainly reduce the amount of requests sent from applications. Within the admin interface the controller file still can't be found. But I guest that requires, as you've mentioned, a special admin integration.

btw. Is it possible to do bulk operations with a single transaction? Or would that even make sense?
At the moment mysql reports the following when inserting two entities with the bulk RPC:

```
         150405 12:41:32     1275 Connect   root@localhost on casalogs
         1275 Query SET NAMES utf8
         1275 Query SELECT t0.id AS id_1, t0.apikey AS apikey_2, t0.private_key AS private_key_3, t0.name AS name_4, t0.created AS created_5, t0.updated AS updated_6 FROM Software t0 WHERE t0.id = 'casa-messenger'
         1275 Query START TRANSACTION
         1275 Query INSERT INTO Msg (timestamp, priority, priority_name, message, extra, created, updated, software_id) VALUES (NULL, NULL, NULL, 'A test message that has been sent through the Advanced Rest Client from chrome (bulk)', NULL, '2015-04-05 12:41:32', '2015-04-05 12:41:32', 'casa-messenger')
         1275 Query commit
         1275 Query START TRANSACTION
         1275 Query INSERT INTO Msg (timestamp, priority, priority_name, message, extra, created, updated, software_id) VALUES (NULL, NULL, NULL, 'A second test message that has been sent through the Advanced Rest Client from chrome (bulk)', NULL, '2015-04-05 12:41:32', '2015-04-05 12:41:32', 'casa-messenger')
         1275 Query commit
         1275 Quit  
```

**Comment by veewee** [comment]
Currently every line in the request is handled independently.
It might be possible to process inserts / updates in bulk, but it requires an extra event when all items are processed. This might be a future feature.
